FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /build

# copy csproj and restore as distinct layers
COPY scr/OtusUserApp.Domain/OtusUserApp.Domain.csproj ./OtusUserApp.Domain/OtusUserApp.Domain.csproj
COPY scr/OtusUserApp.Host/OtusUserApp.Host.csproj ./OtusUserApp.Host/OtusUserApp.Host.csproj
RUN dotnet restore OtusUserApp.Host/OtusUserApp.Host.csproj

# copy everything else and build app
COPY scr ./
RUN dotnet publish OtusUserApp.Host/OtusUserApp.Host.csproj -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:5.0-focal
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "OtusUserApp.Host.dll"]
