FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /build

# copy csproj and restore as distinct layers
COPY scr/EventBus/EventBus.csproj ./EventBus/EventBus.csproj
COPY scr/Billing.Domain/Billing.Domain.csproj ./Billing.Domain/Billing.Domain.csproj
COPY scr/Billing.Host/Billing.Host.csproj ./Billing.Host/Billing.Host.csproj
RUN dotnet restore Billing.Host/Billing.Host.csproj

# copy everything else and build app
COPY scr ./
RUN dotnet publish Billing.Host/Billing.Host.csproj -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:5.0-focal
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "Billing.Host.dll"]