apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "helm.fullname" . }}-config"
data:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "helm.fullname" . }}-files-config"
data: