FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /build

# copy csproj and restore as distinct layers
COPY scr/EventBus/EventBus.csproj ./EventBus/EventBus.csproj
COPY scr/Notification.Domain/Notification.Domain.csproj ./Notification.Domain/Notification.Domain.csproj
COPY scr/Notification.Host/Notification.Host.csproj ./Notification.Host/Notification.Host.csproj
RUN dotnet restore Notification.Host/Notification.Host.csproj

# copy everything else and build app
COPY scr ./
RUN dotnet publish Notification.Host/Notification.Host.csproj -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "Notification.Host.dll"]