FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /build

# copy csproj and restore as distinct layers
COPY scr/Identity/Identity.csproj ./Identity/Identity.csproj
RUN dotnet restore Identity/Identity.csproj

# copy everything else and build app
COPY scr ./
RUN dotnet publish Identity/Identity.csproj -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "Identity.dll"]
