apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: otus-app-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-app
  template:
    metadata:
      labels:
        app: otus-app
    spec:
      containers:
      - name: otus-app
        image: 1vandev/otus-app:v2
        resources:
          limits:
            memory: "32Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
