FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /build

# copy csproj and restore as distinct layers
COPY scr/StockMarket.Shared/StockMarket.Shared.csproj ./StockMarket.Shared/StockMarket.Shared.csproj
COPY scr/StockMarket.Components/StockMarket.Components.csproj ./StockMarket.Components/StockMarket.Components.csproj
COPY scr/StockMarket.Client/StockMarket.Client.csproj ./StockMarket.Client/StockMarket.Client.csproj
RUN dotnet restore StockMarket.Client/StockMarket.Client.csproj

# copy everything else and build app
COPY scr ./
RUN dotnet build StockMarket.Client/StockMarket.Client.csproj -c Release -o /app/build
FROM build AS publish
RUN dotnet publish StockMarket.Client/StockMarket.Client.csproj -c release -o /app/publish --no-restore

# final stage/image
FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY scr/StockMarket.Client/nginx.conf /etc/nginx/nginx.conf