FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /build

# copy csproj and restore as distinct layers
COPY scr/ApiGateway/ApiGateway.csproj ./ApiGateway/ApiGateway.csproj
RUN dotnet restore ApiGateway/ApiGateway.csproj

# copy everything else and build app
COPY scr ./
RUN dotnet publish ApiGateway/ApiGateway.csproj -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:5.0-focal
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "ApiGateway.dll"]
