FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /build

# copy csproj and restore as distinct layers
COPY scr/Account.Domain/Account.Domain.csproj ./Account.Domain/Account.Domain.csproj
COPY scr/Account.Host/Account.Host.csproj ./Account.Host/Account.Host.csproj
RUN dotnet restore Account.Host/Account.Host.csproj

# copy everything else and build app
COPY scr ./
RUN dotnet publish Account.Host/Account.Host.csproj -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "Account.Host.dll"]
