{
 "title": "grafana-dashboard",
 "time": { "from": "2021-02-12T16:15:09.000Z", "to": "2021-02-12T17:03:09.000Z" },
 "panels": [
  {
   "title": "Latency max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, \r\n      sum by (le, action) \r\n         (rate(http_request_duration_seconds_bucket[1m]))\r\n) * 1000",
     "legendFormat": "max {{action}}"
    }
   ]
  },
  {
   "title": "Latency 0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \r\n      sum by (le, action) \r\n         (rate(http_request_duration_seconds_bucket[1m]))\r\n) * 1000\r",
     "legendFormat": "0.5 {{action}}"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n      sum by (le, action) \r\n         (rate(http_request_duration_seconds_bucket[1m]))\r\n) * 1000",
     "legendFormat": "0.99 {{action}}"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n      sum by (le, action) \r\n         (rate(http_request_duration_seconds_bucket[1m]))\r\n) * 1000",
     "legendFormat": "0.95 {{action}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (action) (rate(http_requests_received_total[1m])) ",
     "legendFormat": "RPS{{action}}"
    }
   ]
  },
  {
   "title": "Count 500",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (action) (rate(http_request_duration_seconds_count{code=\"500\"}[1m]))",
     "legendFormat": "Count 500 {{action}}"
    }
   ]
  }
 ]
}