FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /build

# copy csproj and restore as distinct layers
COPY scr/EventBus/EventBus.csproj ./EventBus/EventBus.csproj
COPY scr/Order.Domain/Order.Domain.csproj ./Order.Domain/Order.Domain.csproj
COPY scr/Order.Host/Order.Host.csproj ./Order.Host/Order.Host.csproj
RUN dotnet restore Order.Host/Order.Host.csproj

# copy everything else and build app
COPY scr ./
RUN dotnet publish Order.Host/Order.Host.csproj -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:5.0-focal
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "Order.Host.dll"]