apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "helm.fullname" . }}-config"
data:
  IDENTITY_SERVER_URL: "http://identity-service"
  ORCHESTRATOR_TYPE: "K8S"
  USE_POD_SERVICE_ACCOUNT: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "helm.fullname" . }}-files-config"
data:
{{ (.Files.Glob "gatewayConfig/*").AsConfig | indent 2 }}