apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "helm.fullname" . }}-config"
data:
  IDENTITY_SERVER_URL: "http://identity.arch.homework"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "helm.fullname" . }}-files-config"
data:
  ocelot.json: |-
    {{ .Files.Get "gatewayConfig/ocelot.json" }}