version: '3.7'

services:
  account:
    container_name: account
    build: 
      context: .
      dockerfile: docker/Account/dockerfile
  gateway:
    container_name: gateway
    build: 
      context: .
      dockerfile: docker/ApiGateway/dockerfile
  identity:
    container_name: identity
    build: 
      context: .
      dockerfile: docker/Identity/dockerfile