version: '3.7'

services:
  otus-user-app:
    container_name: otus-user-app
    build: 
      context: .
      dockerfile: docker/dockerfile
    environment:
    - ASPNETCORE_URLS=https://+:443;http://+:80
    - ASPNETCORE_Kestrel__Certificates__Default__Password=qweqwe123
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    
    - USERS_PG_HOST=db-dev
    - USERS_PG_PORT=5432
    - USERS_PG_DATABASE=otus-users
    - USERS_PG_USERNAME=postgres
    - USERS_PG_PASSWORD=qweqwe123
    - USE_SSL_PG_CONNECTION=false

    ports:
    - 8000:80
    - 8001:443
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
    - db-dev
    restart: always
    networks:
    - default

  db-dev:
    container_name: otus-user-app-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: qweqwe123
    volumes:
    - pgdata-dev:/var/lib/postgresql/data
    ports:
    - 7654:5432
    networks:
    - default

networks:
  default:
    name: otus-user-app-network

volumes:
  pgdata-dev:


