apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "helm.fullname" . }}-migration-job"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
         app: "{{ include "helm.fullname" . }}-migration-job"
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              value: {{ include "postgresql.fullname" . | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgresql.service.port | quote }}
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT; 
              do echo waiting for database; sleep 2; done;
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: CASH_TRANSACTIONS_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "helm.fullname" . }}-secret"
                  key: CASH_TRANSACTIONS_PG_PASSWORD
            - name: CASH_TRANSACTIONS_PG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: "{{ include "helm.fullname" . }}-config"
                  key: CASH_TRANSACTIONS_PG_DATABASE
            - name: CASH_TRANSACTIONS_PG_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: "{{ include "helm.fullname" . }}-config"
                  key: CASH_TRANSACTIONS_PG_USERNAME
            - name: USE_SSL_PG_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: "{{ include "helm.fullname" . }}-config"
                  key: USE_SSL_PG_CONNECTION
            - name: MIGRATION_MODE
              valueFrom:
                configMapKeyRef:
                  name: "{{ include "helm.fullname" . }}-config"
                  key: MIGRATION_MODE_TRUE
            - name: ORCHESTRATOR_TYPE
              valueFrom:
                configMapKeyRef:
                  name: "{{ include "helm.fullname" . }}-config"
                  key: ORCHESTRATOR_TYPE
            - name: IDENTITY_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: "{{ include "helm.fullname" . }}-config"
                  key: IDENTITY_SERVER_URL
            - name: ACCOUNT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: "{{ include "helm.fullname" . }}-config"
                  key: ACCOUNT_SERVICE_URL
            - name: EVENT_BUS_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: "{{ include "helm.fullname" . }}-config"
                  key: EVENT_BUS_CONNECTION
            - name: QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: "{{ include "helm.fullname" . }}-config"
                  key: QUEUE_NAME