# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 1vandev/account
  tag: "v1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: account.homework
      paths:
      - path: /($|/)(.*)
        pathType: Prefix
        backend:
          service:
            name: account-service
            port:
              number: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 1000m
    memory: 256Mi
 
postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: accountdb
  service:
    port: "5432"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

externalPostgresql:
  useSsl: false

metrics:
  serviceMonitor:
    enabled: true